### ISSUE TITLE
Feature: Add support for missing IAM Policy Elements

### ISSUE THREAD

**Issue by kallidean** [salesforce/policy_sentry#129]
This would be an incredibly useful tool for us if it could support :
- Principal, 
- NotPrincipal,
- NotResource
 Policy elements.

Is there an inherent challenge to supporting these elements, or does the team feel they are not critical?  Our organization uses them regularly in our cloud resource security standard, and we are very interested in this project as it seems to fit our needs extremely well.

If resource constraints are preventing the project from rolling support for these missing elements, maybe our team could contribute.

**Comment by kmcquade** [comment]
@kallidean - Glad you like it :) I hadn't prioritized that in the roadmap because we focused on identity-based policies rather than resource-based policies. Also, I still hadn't figured out the best way to do Condition Keys support - so that was highest on the list of priorities.

I definitely appreciate your offer to contribute; resource constraints and other priorities with this tool are the factors that are stopping me from extending the tool to support those. However, if your team were to contribute, I'd definitely accept pull requests, and be available for any questions. I'm also available via the Gitter project for this ([![Join the chat at https://gitter.im/salesforce/policy_sentry](https://badges.gitter.im/salesforce/policy_sentry.svg)](https://gitter.im/salesforce/policy_sentry?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)) as well.

**Comment by kmcquade** [comment]
We decided not to support this. 

## Rationale 

Resource-based policies - which leverage `Principal` and `NotPrincipal` - should be carefully, carefully written. Just like user-based policies, resource-based policies tend to (and should) undergo more scrutiny than policies for machine roles. Organizations can achieve this by leveraging infrastructure as code and requiring the use of common Terraform modules or CloudFormation templates for those resource based policies across your organization based on common patterns.

Policy Sentry seeks to programmatically improve the process of writing policies for machine roles, which don't necessarily need to undergo action by action scrutiny - they can just follow access levels and resource ARNs, and that is fine. However, with resource based policies, you might want to more closely inspect individual actions that might be under the same access level and resource ARN. Policy Sentry is not meant to support that level of policy writing scrutiny programmatically.

We want to keep Policy Sentry out of the business of resource based policies, and potentially risky IAM policy elements like `NotResource` or `NotAction`. 

I have considered making the Policy Sentry library more pluggable so this could be potentially feasible from library usage. But I feel like it would be difficult to engineer that so that the policies could be written at scale. 

While we could revise the library so that you are **able** to use Policy Sentry to write those kinds of policies, there's also the question of whether or not we **should**.

At this time, we aren't going to proceed with this kind of feature. 

## Guidance for those who would like to build this on their own

If someone would like to try this out for a separate library, I encourage you to leverage the common functions available in the documentation, which can aid you in your quest. Specifically those leveraged by the query function. The library usage is detailed in the [Library Usage section of the documentation](https://policy-sentry.readthedocs.io/en/latest/library-usage/) and examples are available in [examples/library-usage](https://github.com/salesforce/policy_sentry/tree/master/examples/library-usage).

If you do want to go down this path, we are happy to provide guidance based on library usage.
* Our community can be engaged via the Gitter ([![Join the chat at https://gitter.im/salesforce/policy_sentry](https://badges.gitter.im/salesforce/policy_sentry.svg)](https://gitter.im/salesforce/policy_sentry?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge))
* You can always DM me on Twitter ([kmcquade3](https://twitter.com/kmcquade3)).
