### ISSUE TITLE
ECS Capacity Provider permissions not appearing in local database

### ISSUE THREAD

**Issue by brianelliott-wt** [salesforce/policy_sentry#220]
Hi,

I'm not sure if this is a policy sentry issue or an aws doc's issue where you pull the data from, but I seem to be unable to use any Capacity Provider actions or arns for ECS with the policy_sentry tool even after running a `--fetch` and a `--build` through initialize.

Capacity provider was recently added to the AWS APIs, so I imagine the documentation for its permissions are newer.

https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonelasticcontainerservice.html#amazonelasticcontainerservice-capacity-provider

```
$ policy_sentry query arn-table --service ecs 
                 
arn:${Partition}:ecs:${Region}:${Account}:cluster/${ClusterName}
arn:${Partition}:ecs:${Region}:${Account}:container-instance/${ContainerInstanceId}
arn:${Partition}:ecs:${Region}:${Account}:service/${ServiceName}
arn:${Partition}:ecs:${Region}:${Account}:task/${TaskId}
arn:${Partition}:ecs:${Region}:${Account}:task-definition/${TaskDefinitionFamilyName}:${TaskDefinitionRevisionNumber}
arn:${Partition}:ecs:${region}:${Account}:task-set/${ClusterName}/${ServiceName}/${TaskSetId}
```
```
$ policy_sentry query action-table --service ecs

ALL ecs actions:
ecs:CreateCluster
ecs:CreateService
ecs:CreateTaskSet
ecs:DeleteAccountSetting
ecs:DeleteAttributes
ecs:DeleteCluster
ecs:DeleteService
ecs:DeleteTaskSet
ecs:DeregisterContainerInstance
ecs:DeregisterTaskDefinition
ecs:DescribeClusters
ecs:DescribeContainerInstances
ecs:DescribeServices
ecs:DescribeTaskDefinition
ecs:DescribeTaskSets
ecs:DescribeTasks
ecs:DiscoverPollEndpoint
ecs:ListAccountSettings
ecs:ListAttributes
ecs:ListClusters
ecs:ListContainerInstances
ecs:ListServices
ecs:ListTagsForResource
ecs:ListTaskDefinitionFamilies
ecs:ListTaskDefinitions
ecs:ListTasks
ecs:Poll
ecs:PutAccountSetting
ecs:PutAccountSettingDefault
ecs:PutAttributes
ecs:RegisterContainerInstance
ecs:RegisterTaskDefinition
ecs:RunTask
ecs:StartTask
ecs:StartTelemetrySession
ecs:StopTask
ecs:SubmitAttachmentStateChanges
ecs:SubmitContainerStateChange
ecs:SubmitTaskStateChange
ecs:TagResource
ecs:UntagResource
ecs:UpdateContainerAgent
ecs:UpdateContainerInstancesState
ecs:UpdateService
ecs:UpdateServicePrimaryTaskSet
ecs:UpdateTaskSet
```

Running version 0.8.4

**Comment by kmcquade** [comment]
Ah. Glad you pointed this out. 

It seems like at some point we stopped placing conditions on the loading of the IAM definition path, which means that while the data source would be updated in `~/.policy_sentry/iam-definition.json`, it wasn't actually being leveraged by Policy Sentry.  

![image](https://user-images.githubusercontent.com/3422255/92305690-7b6aa000-ef57-11ea-9725-13afa895762f.png)

I'm going to make a modification so that:
* in `policy_sentry/shared/iam_definition.py`, there is an if/else statement that checks for the existence of the local datastore path. If it exists, leverage that file and then display an info level logging message (info is the default level) letting the user know that they are using the local data store. 
  * Leaving it at `info` level will help users avoid issues where they run `initialize` at some point and then forget that they are using the local datastore path.
  * If users want to disable that check, they can specify `-v critical`, `-v error`, or `-v warning`.

This should be fixed shortly.
