### ISSUE TITLE
Missing permissions for elasticloadbalancing

### ISSUE THREAD

**Issue by nitrocode** [salesforce/policy_sentry#226]
For instance, `elasticloadbalancing:SetSecurityGroups` does not show up when running this command.

```bash
✗ policy_sentry --version
policy_sentry, version 0.8.6
✗ policy_sentry query action-table --service elasticloadbalancing --fmt yaml
ALL elasticloadbalancing actions:
- elasticloadbalancing:AddTags
- elasticloadbalancing:ApplySecurityGroupsToLoadBalancer
- elasticloadbalancing:AttachLoadBalancerToSubnets
- elasticloadbalancing:ConfigureHealthCheck
- elasticloadbalancing:CreateAppCookieStickinessPolicy
- elasticloadbalancing:CreateLBCookieStickinessPolicy
- elasticloadbalancing:CreateLoadBalancer
- elasticloadbalancing:CreateLoadBalancerListeners
- elasticloadbalancing:CreateLoadBalancerPolicy
- elasticloadbalancing:DeleteLoadBalancer
- elasticloadbalancing:DeleteLoadBalancerListeners
- elasticloadbalancing:DeleteLoadBalancerPolicy
- elasticloadbalancing:DeregisterInstancesFromLoadBalancer
- elasticloadbalancing:DescribeInstanceHealth
- elasticloadbalancing:DescribeLoadBalancerAttributes
- elasticloadbalancing:DescribeLoadBalancerPolicies
- elasticloadbalancing:DescribeLoadBalancerPolicyTypes
- elasticloadbalancing:DescribeLoadBalancers
- elasticloadbalancing:DescribeTags
- elasticloadbalancing:DetachLoadBalancerFromSubnets
- elasticloadbalancing:DisableAvailabilityZonesForLoadBalancer
- elasticloadbalancing:EnableAvailabilityZonesForLoadBalancer
- elasticloadbalancing:ModifyLoadBalancerAttributes
- elasticloadbalancing:RegisterInstancesWithLoadBalancer
- elasticloadbalancing:RemoveTags
- elasticloadbalancing:SetLoadBalancerListenerSSLCertificate
- elasticloadbalancing:SetLoadBalancerPoliciesForBackendServer
- elasticloadbalancing:SetLoadBalancerPoliciesOfListener
```

There are additional permissions missing when comparing [policysimulator](https://policysim.aws.amazon.com/home/index.jsp?#) or [cloudonaut](https://iam.cloudonaut.io/reference/elasticloadbalancing.html) to `policy_sentry`.

**Comment by kmcquade** [comment]
Hey @nitrocode,

Great find. We pull our IAM data from the [Actions, Resources, and Condition Keys](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_actions-resources-contextkeys.html) page on the AWS documentation. 

It looks like the page for [Elastic Load Balancing](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_elasticloadbalancing.html) and [Elastic Load Balancing v2](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_elasticloadbalancingv2.html) are separate - even though they share the same IAM service prefix (`elasticloadbalancing`).

@nitrocode - the actions that you see above are from the page for Elastic Load Balancing (v1). I will take a look at the scraping and then see how we can adjust so that it includes all the actions from v2 as well.

FYI @0xdabbad00 in case this impacts Parliament, since we use the same scraping approach there.

**Comment by kmcquade** [comment]
It looks like the scraping is storing the information fine - but as a separate entry in the `iam_definition` array.

![image](https://user-images.githubusercontent.com/3422255/93238670-bdfa5c80-f74f-11ea-89e3-755ea0cf807e.png)

In retrospect, I should have set the service prefix as the top level key in the IAM definition - but alas, here we are.

I will dig into this and make sure that the queries look for all instances of `elasticloadbalancing`.

**Comment by nitrocode** [comment]
@kmcquade I don't know of any, however, is it possible that there are other AWS scraped pages that share a `prefix` meaning that other services could also show fewer perms ?

**Comment by kmcquade** [comment]
Potentially. Might be best to refactor the structure of the IAM definition so that it is a list rather than an array - which would require changing the query commands.
