### ISSUE TITLE
Missing EKS permissions

### ISSUE THREAD

**Issue by matt-mcc1** [salesforce/policy_sentry#231]
Firstly, nice work on this tool!

When I run `policy_sentry query action-table --service eks` , the output contains: `eks:DescribeCluster` (as an example).

```
ALL eks actions:
eks:CreateCluster
eks:CreateFargateProfile
eks:CreateNodegroup
eks:DeleteCluster
eks:DeleteFargateProfile
eks:DeleteNodegroup
eks:DescribeCluster
eks:DescribeFargateProfile
eks:DescribeNodegroup
eks:DescribeUpdate
eks:ListClusters
eks:ListFargateProfiles
eks:ListNodegroups
eks:ListTagsForResource
eks:ListUpdates
eks:TagResource
eks:UntagResource
eks:UpdateClusterConfig
eks:UpdateClusterVersion
eks:UpdateNodegroupConfig
eks:UpdateNodegroupVersion
```

**When my YAML contains:**

```
mode: crud
name: 'Example'
wildcard-only:
  service-read:
  - 'eks'
  service-list:
  - 'eks'
```

the permission `eks:DescribeCluster` is missing. Only this is output:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "MultMultNone",
            "Effect": "Allow",
            "Action": [
                "eks:ListClusters"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```
This appears to be similar for other resources, such as IAM - where the action-table appears to have correct information but the JSON misses out permissions. 

Policy_Sentry version: version 0.8.7 (installed on Mac via Brew).

**Comment by kmcquade** [comment]
Hey Matt! Actually, this is by design. `eks:DescribeCluster` can actually be restricted to the resource ARN of a specific cluster.

![image](https://user-images.githubusercontent.com/3422255/93601665-84179900-f98f-11ea-9a18-3223e842963a.png)

The `service-wide` option is meant for actions that **do not support resource ARN constraints at all**. An example is `s3:ListAllMyBuckets`.

Template:

```yaml
mode: crud
wildcard-only:
    service-list:
    - s3
``` 

Output:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "MultMultNone",
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

Now let's get to your question. 

There are two options for generating what you want. 

## Option 1: Read and list for All clusters

* "I want read and list access to all clusters"

Template:

```yaml
mode: crud
read:
- 'arn:aws:eks:us-east-1:123456789012:cluster/*'
list:
- 'arn:aws:eks:us-east-1:123456789012:cluster/*'
```

Output:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "EksReadCluster",
            "Effect": "Allow",
            "Action": [
                "eks:DescribeCluster",
                "eks:DescribeUpdate"
            ],
            "Resource": [
                "arn:aws:eks:us-east-1:123456789012:cluster/*"
            ]
        },
        {
            "Sid": "EksListCluster",
            "Effect": "Allow",
            "Action": [
                "eks:ListFargateProfiles",
                "eks:ListNodegroups",
                "eks:ListTagsForResource",
                "eks:ListUpdates"
            ],
            "Resource": [
                "arn:aws:eks:us-east-1:123456789012:cluster/*"
            ]
        }
    ]
}
```

^ This is a good choice when you want:
* the role to always have access to only the actions that apply to the `cluster` resource ARN type. This way, you avoid a situation where you are granting access to all read or all write actions across the entire AWS service.
* You don't care if it applies to **all** clusters

## Option 2: Explicitly Skipping Resource Constraints 

* "I just want eks:DescribeCluster and nothing else"

```yaml
mode: crud
skip-resource-constraints:
- 'eks:DescribeCluster'
```

## Afterthought: Improving the user experience

So, your question brings me one conclusion: The documentation structure needs to be improved. Right now, it looks like the section on two key features is buried under "feature examples". The "skipping resource constraints" is not mentioned earlier and it really should be.

![image](https://user-images.githubusercontent.com/3422255/93602201-52eb9880-f990-11ea-80f6-253dee05aa71.png)

What other changes do you think could be made to the user experience to avoid similar confusion in the future?

**Comment by kmcquade** [comment]
## Afterthought: Improving the user experience

So, your question brings me one conclusion: The documentation structure needs to be improved. Right now, it looks like the section on two key features is buried under "feature examples". The "skipping resource constraints" is not mentioned earlier and it really should be.

From the sidebar in the docs:

> <img src="https://user-images.githubusercontent.com/3422255/93602201-52eb9880-f990-11ea-80f6-253dee05aa71.png" width="256">

What other changes do you think could be made to the user experience to avoid similar confusion in the future?

**Comment by kmcquade** [comment]
A third option exists as well.

## Option 3: Restricting access to `mycluster`

Template:

```yaml
mode: crud
read:
- 'arn:aws:eks:us-east-1:123456789012:cluster/mycluster'
list:
- 'arn:aws:eks:us-east-1:123456789012:cluster/mycluster'
```

Output:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "EksReadCluster",
            "Effect": "Allow",
            "Action": [
                "eks:DescribeCluster",
                "eks:DescribeUpdate"
            ],
            "Resource": [
                "arn:aws:eks:us-east-1:123456789012:cluster/mycluster"
            ]
        },
        {
            "Sid": "EksListCluster",
            "Effect": "Allow",
            "Action": [
                "eks:ListFargateProfiles",
                "eks:ListNodegroups",
                "eks:ListTagsForResource",
                "eks:ListUpdates"
            ],
            "Resource": [
                "arn:aws:eks:us-east-1:123456789012:cluster/mycluster"
            ]
        }
    ]
}
```

**Comment by matt-mcc1** [comment]
Superb!! Fantastic response, this makes complete sense to me now. 

This has solved my issue so will close ticket, will have a think about your UX question and post back (on a separate ticket). 

Thanks, appreciate your help 👍

**Comment by kmcquade** [comment]
For sure! Glad it helps. 

Feel free to open up an issue or DM me anytime if you're on Twitter or the cloud security forum slack!
