### ISSUE TITLE
get empty policy when trying to give resource constraint access to a role Arn

### ISSUE THREAD

**Issue by samchecc** [salesforce/policy_sentry#244]
Whenever I want to apply write access to an aim role Arn, the policy generated is empty

-----------------------------------

from policy_sentry.writing.template import get_crud_template_dict
from policy_sentry.command.write_policy import write_policy_with_template
import json

if __name__ == '__main__':
    crud_template = get_crud_template_dict()
    crud_template['write'].append("arn:aws:iam::123456789012:role/testing")

    policy = write_policy_with_template(crud_template)
    print(json.dumps(policy, indent=4))

"""
Output:
{
    "Version": "2012-10-17",
    "Statement": []
}
"""

**Comment by kmcquade** [comment]
@samchecc that is because we treat any "Write" level actions in IAM, RAM, and DS as Permissions Management actions. 

https://github.com/salesforce/policy_sentry/blob/master/policy_sentry/shared/data/access-level-overrides.yml#L159

This should work for you:

`crud_template['permissions-management'].append("arn:aws:iam::123456789012:role/testing")`
