### ISSUE TITLE
Errors on Mac querying/all list has no keys attribute

### ISSUE THREAD

**Issue by ntkach** [salesforce/policy_sentry#283]
At some point fairly recently (honestly I don't know, I'm estimating in the last 3 months maybe) policy_sentry cli has stopped working.  This is on MacOS 10.14.6.  Using pyenv I've tried python-3.7.9, python-3.7.8, python-3.8.6, python-3.9.0.  Yes I know, I found mention later on re no guarantees with python >= 3.8.  Tried both the pip3 packaged version and the source code version.  Tried both policy-sentry-0.9.1 and policy-sentry-0.10.0.  No matter what I do soon as I try to do anything invoking the command-line `policy_sentry` I get an error.  Same error each time

`policy_sentry-0.9.1 ntkach$ policy_sentry
Traceback (most recent call last):
  File "/Users/ntkach/.pyenv/versions/3.7.9/bin/policy_sentry", line 5, in <module>
    from policy_sentry.bin.cli import main
  File "/Users/ntkach/.pyenv/versions/3.7.9/lib/python3.7/site-packages/policy_sentry/bin/cli.py", line 7, in <module>
    from policy_sentry import command
  File "/Users/ntkach/.pyenv/versions/3.7.9/lib/python3.7/site-packages/policy_sentry/command/__init__.py", line 3, in <module>
    from policy_sentry.command import write_policy
  File "/Users/ntkach/.pyenv/versions/3.7.9/lib/python3.7/site-packages/policy_sentry/command/write_policy.py", line 10, in <module>
    from policy_sentry.writing.sid_group import SidGroup
  File "/Users/ntkach/.pyenv/versions/3.7.9/lib/python3.7/site-packages/policy_sentry/writing/sid_group.py", line 6, in <module>
    from policy_sentry.analysis.expand import determine_actions_to_expand
  File "/Users/ntkach/.pyenv/versions/3.7.9/lib/python3.7/site-packages/policy_sentry/analysis/expand.py", line 6, in <module>
    from policy_sentry.util.policy_files import get_actions_from_statement
  File "/Users/ntkach/.pyenv/versions/3.7.9/lib/python3.7/site-packages/policy_sentry/util/policy_files.py", line 5, in <module>
    from policy_sentry.querying.actions import get_action_data
  File "/Users/ntkach/.pyenv/versions/3.7.9/lib/python3.7/site-packages/policy_sentry/querying/actions.py", line 12, in <module>
    all_service_prefixes = get_all_service_prefixes()
  File "/Users/ntkach/.pyenv/versions/3.7.9/lib/python3.7/site-packages/policy_sentry/querying/all.py", line 21, in get_all_service_prefixes
    results = list(set(iam_definition.keys()))
AttributeError: 'list' object has no attribute 'keys'`

It's always the same.  For whatever reason python seems to keep trying to get a keys attribute off that iam_definition before the (I'm assuming) "cast" to a set.

I'd be more than happy to provide more specific details.

**Comment by saikirankv** [comment]
@ntkach  can you run `cat /Users/ntkach/.pyenv/versions/3.7.9/lib/python3.7/site-packages/policy_sentry/shared/data/iam-definition.json` and check if there is any data in this file.

**Comment by ntkach** [comment]
Yep, @saikirankv about 5.7mb.  Just glancing at head and tail and a little of the middle looks like plausibly valid json.  I can post more, but here's the head
`{
    "a4b": {
        "service_name": "Alexa for Business",
        "prefix": "a4b",
        "privileges": {
            "ApproveSkill": {
                "privilege": "ApproveSkill",
                "description": "Associates a skill with the organization under the customer's AWS account. If a skill is private, the user implicitly accepts access to this skill during enablement.",
                "access_level": "Write",
                "resource_types": {`

**Comment by kmcquade** [comment]
Can you run Policy sentry initialize again? It might be the local IAM definition JSON file being in the old format

**Comment by kmcquade** [comment]
@ntkach - Policy Sentry will default to the file in your home directory if it is there.

The IAM definition JSON file was structured differently in the past - specifically, it was a list instead of a dictionary, which caused some speed issues if Policy Sentry was used heavily as a Python dependency (like the Cloudsplaining project). We introduced changes in the IAM Definition JSON file in #240. After that version, if you still had a file titled `iam-definition.json` in `/Users/kmcquade/.policy_sentry/iam-definition.json` and it was the old format, then Policy Sentry would stop working. I suspect this is what you are facing.

* `/Users/kmcquade/.policy_sentry/iam-definition.json` - this will be there if I ever run `policy_sentry initialize`. If the file exists, Policy Sentry will *always* use that file.
* If you never run `policy_sentry initialize` it will just use the `iam-definition.json` that is embedded in the python package.

I suggest you do one of the following:

* Option 1: `rm $HOME/.policy_sentry/iam-definition.json`. This will just remove the old IAM Definition JSON so you can use the embedded one by default.
* Option 2: `policy_sentry initialize`. This will just write the IAM Definition JSON file over the old one.

**Comment by ntkach** [comment]
@kmcquade Ah thank you very much!  I deleted the ~/.policy-sentry/iam-definition.json and it started working again.

**Comment by ntkach** [comment]
This is resolved so I'm closing it out.

**Comment by kmcquade** [comment]
Awesome :) Glad it worked out
