### ISSUE TITLE
Missing AWS Glue Blueprint actions

### ISSUE THREAD

**Issue by leonardoviveiros** [salesforce/policy_sentry#371]
AWS Glue Blueprints are [kind of new](https://aws.amazon.com/about-aws/whats-new/2021/03/aws-announces-preview-aws-glue-custom-blueprints/), and not even official [AWS Docs](https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsglue.html) covered them yet. But it would be nice if Policy Sentry adds it.
The action that impacted us is glue:ListBlueprints, but I believe there's more than just list action.

I'd love to help implement this, if possible.

**Comment by kmcquade** [comment]
@leonardoviveiros is `glue:ListBlueprints` an actual action? I don't see it anywhere and we just scraped the last AWS IAM Docs

**Comment by kmcquade** [comment]
@leonardoviveiros - yeah, it looks like those are legitimate actions but are still undocumented, per @iann0036's permissions.cloud reference. See here: https://permissions.cloud/iam/glue. 

Here's how we generate the IAM data for context - Right now, GitHub actions runs a script (see [here](https://github.com/salesforce/policy_sentry/blob/master/utils/download_docs.py)) monthly to scrape the [AWS SAR Documentation](https://docs.aws.amazon.com/service-authorization/latest/reference/reference_policies_actions-resources-contextkeys.html) and compile the latest IAM data. It stores that data in [iam-definition.json](https://github.com/salesforce/policy_sentry/blob/master/policy_sentry/shared/data/iam-definition.json).

The real fix for this would be leveraging Ian's IAM data set instead of the  current setup above. https://permissions.cloud is the most up to date, robust, and quality set out there. He’s cleaned up the data considerably more than any of us out there. Parliament’s data set and Policy Sentry’s data set are practically the same (based on scraping the SAR docs). Other tools use the policies.his script mentioned above. But Ian’s data set leverages the actual API definitions in the SDK, the SAR docs, and a ton of error corrections and his own custom mapping. And it’s all reflected in that website. His is the gold standard now, both for machine readable and user friendly display of “all the stuff you can do with IAM.”

To move to his data set, we'd need to:
1. Figure out how his code works
2. Modify the [query functions](https://github.com/salesforce/policy_sentry/tree/master/policy_sentry/querying) to leverage that code. Policy Sentry uses those functions to perform most of its IAM data lookups, as those functions abstract the queries to the database.
3. Modify unit tests etc to reflect any changes

I can't make those modifications on my end, as this would require a lot of changes that I don't have capacity for. However, given that this would benefit a lot of people, I'd certainly review a robust PR and be available for messaging/questions/ideas if that's something you wanted to take on.

**Comment by iann0036** [comment]
You should be able to directly use the [iam_definition.json](https://raw.githubusercontent.com/iann0036/iam-dataset/main/iam_definition.json) file from the IAM dataset repo if you like. Notably, this has two changes that may affect your handling:

* The addition of "Unknown" as an access_level
* Conflation of related services, such as V2 APIs

**Comment by leonardoviveiros** [comment]
Thank @kmcquade and @iann0036 for the information, it's a lot to digest.
I'm trying to understand the project now, to plan how to handle the changes I need to use iam_definition.json as the source.
I may need some help in the future if that's okay!

**Comment by kmcquade** [comment]
Sure, feel free to reach out!

**Comment by knasty51** [comment]
I took a stab at this because I think this would be a good direction to consume an already sanitized source of truth for IAM. I hope you don't mind the initiative. Here is what I've observed while making these changes. You can see them here https://github.com/knasty51/policy_sentry/tree/feature/newIamDefinitionFile

1. As mentioned above, the unknown actions and how to handle. I don't think adding `--access-level unknown` or including a flag for `--include-unknown-actions` is the way to go. It should either be done by the overrides YAML file or I've written a function to "infer" the access level based on other services actions with similar names. Let me know what you think.
2. I had to modify some tests due to AWS updating their actions (I imagine this is common)
3. Speed - since the iam-definitions.json from the provided repo is a list of dictionaries, service lookups are theoretically slower, though I didn't notice a huge difference when using the binary. The way the data was originally arranged with dictionaries made look ups fast, but I adapted to the file structure provided. Another way to tackle this would be to download the iam-definitions.json and restructure it to the original implementation.
4. I had to make some assumptions about the documentation links since those are not provided in the JSON either. As long as AWS is consistent in their documentation naming scheme, it should work. But the URLs generated are best guesses. We could combine the docs scraping with the JSON download, or ask the maintainer to add these fields.
5. New task for downloading the iam-definitions.json and create_database function that writes to the file.
6. Side note: I'm using a Mac and the Makefile prefers PROJECT_UNDERSCORE for install as opposed to PROJECT but I did not commit that change.

I did verify all tests pass and the command `policy_sentry query action-table --service glue --resource-type "*" --fmt yaml -a write` returns the write actions including Blueprint (based on the inferences of access_level)
```
glue WRITE actions that have the resource type *:
- glue:BatchGetBlueprints
- glue:BatchStopJobRun
- glue:CreateBlueprint
- glue:CreateClassifier
- glue:CreateCrawler
- glue:CreateDevEndpoint
- glue:CreateJob
- glue:CreateMLTransform
- glue:CreateScript
- glue:CreateSecurityConfiguration
- glue:CreateSession
- glue:CreateTrigger
- glue:CreateWorkflow
- glue:DeleteBlueprint
- glue:DeleteClassifier
- glue:DeleteSecurityConfiguration
- glue:ResetJobBookmark
- glue:StartBlueprintRun
- glue:StartCrawlerSchedule
- glue:StartJobRun
- glue:StopCrawlerSchedule
- glue:UpdateBlueprint
- glue:UpdateClassifier
- glue:UpdateCrawlerSchedule
```

**Comment by kmcquade** [comment]
That's awesome! Can you make a PR?

Would appreciate input from @jsmartin on this one, as this could potentially have downstream impacts on DivvyCloud

**Comment by knasty51** [comment]
Managed to get a better infer access level function before opening the PR. The tests pass, but I feel like there are inconsistencies particularly with glue but that could be due to additional actions in the new source. Would definitely appreciate your input.
https://github.com/salesforce/policy_sentry/pull/384

**Comment by kmcquade** [comment]
Closing this since we decided not to go with #384. See my rationale here: https://github.com/salesforce/policy_sentry/pull/384#issuecomment-1030419096
