### ISSUE TITLE
Comparision of actions/service in permissions.cloud vs policy_sentry

### ISSUE THREAD

**Issue by jsmartin** [salesforce/policy_sentry#393]
I wrote a quick script to do comparisons between permissions.cloud and policy sentry and have found the following:

```
Total Number of Unique actions in Policy Sentry:  11005
Total Number of Unique actions in permissions.cloud:  11945
Total Number of Unique services in Policy Sentry:  290
Total Number of Unique services in permissions.cloud:  301
Count of services in permissions.cloud but not in Policy Sentry 11
Count of services in Policy Sentry but not in permissions.cloud 0
Count of actions in permissions.cloud but not in Policy Sentry 954
Count of actions in Policy Sentry but not in permissions.cloud 14
```
I've attached a zip file with the script and  files showing the deltas --
[compare.zip](https://github.com/salesforce/policy_sentry/files/7998382/compare.zip)

**Comment by kmcquade** [comment]
Hey so I started taking a look at this. It looks like your IAM definition that you were using was out of date. Try doing `rm -rf ~/.policy_sentry/` and it will remove your locally built database, which will always override the one that is in the package.

When I did this, it reduced the count of actions that are in permissions.cloud but not in Policy Sentry from 954 to 392.

Looking into the remaining ones.

**Comment by kmcquade** [comment]
Okay, here's a Google Sheet with my analysis on the missing actions (anyone can view): https://docs.google.com/spreadsheets/d/1wEbfRHsnEM94RJRkXOCYA4UlY7bOxQ6Mz3hY44u4L0M/edit?usp=sharing

My observations of these actions from the spreadsheet and their possible root causes:
* 124 actions are affected by "Overlap Scenarios" - where there are multiple pages in the SAR documentation for a single IAM namespace. Prime examples: `greengrass`, `apigateway`, `aws-marketplace`, and `lex` all have two or more pages in the SAR documentation. 
* 75 actions are not documented in SAR. Ian's https://aws.permissions.cloud does a great job of reconciling these and I'm just not going to consider those in-scope for Policy Sentry's scraping since (a) I don't have time for it and (b) the AWS team should just fix that. Hopefully that count goes down over time.
* 193 actions - I am not sure about the root cause of those; it is likely something weird in the HTML.

Leaving this data here in case someone wants to dig into the rest of it - I'll try to knock out the Overlap scenarios and will also post here if I end up not having the time.
