### ISSUE TITLE
action-table for iam is incorrect 

### ISSUE THREAD

**Issue by SizableDeMerit** [salesforce/policy_sentry#407]
When I run:
policy_sentry query action-table --service iam --access-level write 
I get [] 

When I run: 
policy_sentry query action-table --service iam --access-level permissions-management
In addition to the PERMISSIONS-MANAGEMENT actions I also get 56 actions that belong under the WRITE category. 

This also impacts trying to write policies. 

Here are the 56 actions the should show up under the WRITE category for IAM 

<img width="927" alt="image" src="https://user-images.githubusercontent.com/102994153/176274741-cdaa5d90-772f-4484-9ba1-1158b120fc42.png">

**Comment by kmcquade** [comment]
Hi! Yes, we actually do a custom override of the access levels, partially because AWS is really bad at keeping the access levels accurate. Here is where that happens for IAM: https://github.com/salesforce/policy_sentry/blob/master/policy_sentry/shared/data/access-level-overrides.yml#L162

I included this because I feel that modifications of any IAM actions are literally permissions management and should be treated as such. Maybe not the UpdateRoleDescription and other description items, but looking at the rest of these, those actions do manage permissions so I kept it like that.

**Comment by SizableDeMerit** [comment]
@kmcquade Thank you for for your prompt response. While I see your intention, as a Cloud Security Professional it is a departure from what we are used to seeing in the AWS platform. It therefore looks like a bug to any AWS professional. I would like to see a tool I am working with in line with the platform I am working on.  It took me a while to discover where you had placed the actions that I expected to find under WRITE. If you were to  place them in a position consistent with the AWS platform it would be more intuitive and save your users time. That's just my 2 cents. Thanks again for sharing your perspective and thank you for developing an awesome tool for security professionals.

**Comment by kmcquade** [comment]
I appreciate the input, thanks!

**Comment by kmcquade** [comment]
`policy_sentry initialize --access-level-overrides-file access-level-overrides.yml`
