### ISSUE TITLE
missing `policy_sentry/shared/data/iam-definition.json` in the 0.13.0 pypi sdist

### ISSUE THREAD

**Issue by chenrui333** [salesforce/policy_sentry#495]
seeing some file missing in the 0.13.0 pypi sdist

```
error: [Errno 2] No such file or directory: 'policy_sentry/shared/data/iam-definition.json'
```

relates to https://github.com/Homebrew/homebrew-core/pull/177982

**Comment by chenrui333** [comment]
not sure what is going on, but `python setup.py sdist` works fine for me (seeing `policy_sentry/shared/data/iam-definition.json` got packaged)

**Comment by gruebel** [comment]
yeah, can't really say, why it was not packed into the dist archive 🤔

**Comment by chenrui333** [comment]
any chance cutting a new release to see if it happens again? (how to verify the release pipeline)

**Comment by kmcquade** [comment]
@gruebel the file is supposed to be included because it is specified in the MANIFEST.in file. setuptools uses MANIFEST.in to determine files it should bundle into the dist. https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html

I am not sure if that was changed in Python 3.12/3.13 but I saw you changed the publisher to use 3.12 recently. Maybe it has something to do with that, or an upgrade to pip.

**Comment by gruebel** [comment]
@chenrui333 sure, I will cut a new release after findind a way to test it properly, so it won't be missing again.

**Comment by gruebel** [comment]
@chenrui333 ok, I think it should work now with version `0.13.1` it looks like it was related to using a very old `setuptools` version during the build process. that's why it worked for you and me locally, because you wouldn't use such an old version 😅 let me know, if everything is ok now.

**Comment by chenrui333** [comment]
0.13.1 works for me. Closing the issue via https://github.com/Homebrew/homebrew-core/pull/177982
